### PR TITLE
Python implementation

### PR DESCRIPTION
**Pull request by rshest**
This is a Python implementation of the same code that is already written in several other languages.

The package is [published to PyPi](https://pypi.python.org/pypi/proquint/0.1.0), so it can be installed simply via:
```bash
pip install proquint
```

Tested to work with Python 2.7, 3.5 and pypy (there is a Tox file).

### CODE REVIEW

**Comment by dsw** [comment]
Thanks.  I'll merge it.  Let me ask you this first though.

Can I get you to make the comments on the encode and decode functions a bit
more symmetric?

This one uses the terms "proquint" and "unit":

    Convert "proquint" string into the corresponding uint representation.

On the other hand, this one uses the terms "quintet" and "32-bit integer":

    Convert 32-bit integer value to character quintet representation.

It seems to me that it would be best to also use the term "proquint" in
both, as well as using "32-bit integer" in both, or at least do something
more uniform between the two.  What do you think?

**Comment by dsw** [comment]
Also, do add your implementation to the list at the top of the Readme:

9 January 2009: initial release
8 April 2012: Java implementation
30 December 2015: Javascript implementation by Luděk Rašek

**Comment by rshest** [comment]
Done, hopefully looks better now.
Thanks a lot!

**Comment by dsw** [comment]
I find the github UI a bit confusing, but I think I merged in your pull
request.  Thank you for the contribution.

**Comment by dsw** [comment]
Hey, could you also add a paragraph in the body of the Readme, just below
this paragraph?

"Java implementation: Proquint.java converts between proquint, hex, and
decimal strings."

On Tue, Oct 3, 2017 at 3:12 PM, Daniel Wilkerson <daniel.wilkerson@gmail.com
> wrote:

> I find the github UI a bit confusing, but I think I merged in your pull
> request.  Thank you for the contribution.
>
> On Tue, Oct 3, 2017 at 2:31 PM, Ruslan Shestopalyuk <

**Comment by rshest** [comment]
Thanks for merging the PR, I've created one more (#8) with some improvements, where I also modified the body of Readme as you asked.

**Pull request merged**
